version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: assessment
      POSTGRES_PASSWORD: assessment
      POSTGRES_DB: assessment
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - posttest-network
  backend:
    build: ./
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://assessment:assessment@db:5432/assessment
    networks:
      - posttest-network

networks:
  posttest-network:
    driver: bridge